### PR TITLE
Add MELCC station data converter + CanSWE

### PR DESCRIPTION
**Pull request by Zeitsperre**

### CODE REVIEW

**Comment by aulemahal** [comment]
I think we need this for the Pins project.
I started something that depends on an external cli tool (`mdbtools`). Accessing ACCESS files through python using something like `pyodbc` seems quite complex on not-windows. But, `mbdtools` (even though I read it is abandoned) is able to export the tables easily.

See : https://gist.github.com/aulemahal/68c29bd9bef1fc9e2c427aa0ec29a3b3

For the missing metadata, I'll try to contact Benoît Charette (or someone else if he's not available).

**Comment by aulemahal** [comment]
So here is my first complete version of the parser/converter.

I was told today by our contact at MELCC that this work had already been done in Ouranos. I thought that the previous work of netCDF conversion only concerned the gridded data (GCQ) but it seems the stations also had been converted by @tlogan2000 ... Woups, I assumed that everything we had was in the "external_data" folder, but:
- if the data was converted to netCDF, it is absent from that folder
- I was told a lot more was transferred to Ouranos than what I found in the `obs_raw` zip files.

Anyway, here is my converter code. It required `mdbtools` to run and as such can't parse data from before 1900 (see mdbtools/mdbtools#367).

The `convert.py` file is meant as a script with some arguments.

It requires a xlsx file with the station information, file that I copied to the internal directory where the rest lies.

For now, `attrs.json` only has metadata for the variables I found in the two zip files.

Finally, we are missing the "priority" logic to merge data from multiple instruments taken at the same time and place. The current code merges everything with highest priority to the lowest instrument code, which is surely not very good.

**Comment by tlogan2000** [comment]
FYI to do some of the the initial work on this data with @Zeitsperre I believe I has to convert .mdb to .csv (or excel ?) via arcpy which is windows only (not the best solution but was in a bit of a time crunch).  Ideally MELCC folks could provide us with a format other than .mdb.  I believe their database is in oracle so we might be able to request they give us something like sqlite instead?

**Comment by aulemahal** [comment]
@Zeitsperre The last commits have a working version of the MDB converter for MELCC data, but also for the 2sem snow data from the MELCC (which comes in an excel file, so I added the `openpyxl` dependency). And for CanSWE data (in a new `ec.py` file).

**Pull request merged**
