### PR TITLE
Add cordex aws downloader function

### PR DESCRIPTION
**Pull request by Zeitsperre**

### CODE REVIEW

**Comment by aulemahal** [comment]
Question : what is the reason to use the AWS version instead of the official esgf node?

Also, if you could convert the calendar back to the correct one, that could be nice. See: https://github.com/Ouranosinc/scenarios_generiques/blob/8c85b847cd26b8c10b0590cc9ed5c30ec346d0f2/bias_adjust/workflow/io.py#L200-L215

**Comment by Zeitsperre** [comment]
The AWS version can be downloaded without OAuth certification, so that's a big plus. For the calendar fixes, I could copy and patch that function in here. Would you be alright with that?

**Comment by aulemahal** [comment]
I see! No problemo. As you see, I kinda hardcoded the 360_day conversion, but it seems to work!

**Comment by aulemahal** [comment]
I can't find the call of the function, is it implicit?
The function does return a new object : some operations are inplace, but `convert_calendar` isn't!

**Comment by Zeitsperre** [comment]
This is currently running. Outputs look good!

**Pull request merged**
